language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - python setup.py install
  - coverage run --source=glances --omit="glances_bottle,glances_color_console,glances_csv,glances_curses" unitest.py
after_success:
  - coveralls